# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiDraftWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(533, 380)
        self.draftTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.draftTextEdit.setGeometry(QtCore.QRect(30, 50, 471, 211))
        self.draftTextEdit.setObjectName("draftTextEdit")
        self.historyButton = QtWidgets.QPushButton(Form)
        self.historyButton.setGeometry(QtCore.QRect(30, 310, 75, 23))
        self.historyButton.setObjectName("historyButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Draft"))
        self.historyButton.setText(_translate("Form", "History"))
